inherit_from:
  - .rubocop_airbnb.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/**/*'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'path/ruby'
    - 'Gemfile'
    - 'spec/spec_helper.rb'
    - 'node_modules/**/*'
